// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetData(arg1) {
  return window['go']['main']['App']['GetData'](arg1);
}

export function GetStartupData() {
  return window['go']['main']['App']['GetStartupData']();
}

export function ResetTask(arg1) {
  return window['go']['main']['App']['ResetTask'](arg1);
}

export function SendFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendFile'](arg1, arg2, arg3);
}
