// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetData(arg1:string):Promise<string>;

export function GetStartupData():Promise<main.StartupData>;

export function ResetTask(arg1:string):Promise<string>;

export function SendFile(arg1:string,arg2:string,arg3:string):Promise<main.SendFileResponse>;
