// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetData(arg1: string): Promise<string>;

export function GetLatestSubmission(arg1: string): Promise<main.SubmissionStatus>;

export function GetStartupData(): Promise<main.StartupData>;

export function GetSubmissionHistory(arg1: string): Promise<Array<main.SubmissionStatus>>;

export function GetSubmissionStatus(arg1: string): Promise<main.SubmissionStatus>;

export function ResetTask(arg1: string): Promise<string>;

export function SendFile(arg1: string, arg2: string, arg3: string): Promise<main.SendFileResponse>;

export function StartSession(arg1: main.StartSessionRequest): Promise<main.StartupData>;
